[workspace]
resolver = "2"
members = [
  "argentum_game",
  "argentum_game_voxel",
  "argentum_game_coordinate_system",
  "argentum_game_world_generator",
  "argentum_game_world_data",
]

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
